// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDlKXVF8ErhfHJlY7cnGPtPBBNjGTWUo',
    appId: '1:1087136187556:web:76efa2b23e53c869be1231',
    messagingSenderId: '1087136187556',
    projectId: 'agora-audio-call-app',
    authDomain: 'agora-audio-call-app.firebaseapp.com',
    storageBucket: 'agora-audio-call-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANcQHhZnXTptmBhtKioXqTdiQfG1RU7J8',
    appId: '1:1087136187556:android:cc03caffb3daeecfbe1231',
    messagingSenderId: '1087136187556',
    projectId: 'agora-audio-call-app',
    storageBucket: 'agora-audio-call-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJNIWcp3waKwrUJe0mtgpqXLVN1BmKRow',
    appId: '1:1087136187556:ios:4b1b638106e94b12be1231',
    messagingSenderId: '1087136187556',
    projectId: 'agora-audio-call-app',
    storageBucket: 'agora-audio-call-app.appspot.com',
    iosBundleId: 'com.example.videoCalling',
  );
}
